spring:
  profiles:
    active: @env@
  application:
    name: zongheng-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 0
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
#    #不要为我们工程中的资源文件建立映射
    add-mappings: false
#  messages:
#    basename: il8n/
  datasource:
    druid:
      url: @datasource.url@
      driverClassName: @datasource.driver@
      username: @datasource.username@
      password: @datasource.password@
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        #login-username: admin
        #login-password: admin
        enabled: true
        url-pattern: /druid/*
      # 初始化连接大小   默认：0
      initial-size: 5
      # 最小空闲连接数 默认：0
      min-idle: 5
      # 最大连接数  默认：8
      max-active: 20
      # 获取连接等待超时的时间(毫秒) 默认：-1
      max-wait: 60000
      # 查询超时时间(秒)
      query-timeout: 90
      # 用来检测连接是否有效的sql，要求是一个查询语句
      # validation-query: SELECT 1 FROM DUAL
      # 申请连接时检测连接可用性 默认：false
      test-on-borrow: false
      # 归还连接检测 默认：false
      test-on-return: false
      # 超时是否检测连接可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接 (毫秒)
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间(毫秒，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat；日志用的filter:log4j；防御sql注入的filter:wall
      filters: slf4j
      # 慢SQL记录 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
      filter:
        slf4j:
          statement-executable-sql-log-enable: true
      # 是否缓存PreparedStatement. PSCache对支持游标的数据库性能提升巨大，比如说oracle.在mysql下建议关闭.
      pool-prepared-statements: false
      # 每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.zenith.**.domain.entity
  global-config:
    db-config:
      id-type: id_worker
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
